spring:
  application:
    name: microservicecloud-config-client
#  cloud:
#    config:
#      uri: http://config-3344.com:3344
#      name: microservicecloud-config-client
#      profile: test
#      label: master
