server:
  port: 80


eureka:
  instance:
    instance-id: microservicecloud-consumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7001/eureka
spring:
  application:
    name: microservicecloud-consumer-80